export const sections = [
  {
    id: 'all',
    label: 'All Projects',
    description:
      'Here&rsquo;s a little bit of everything.  Some are pretty random... some are *really* old. For my web projects, so many of these either no longer exist, or have been redeveloped since I launched them. Archived links *might* be available upon request.',
    seo: "Here is a few of the various projects I've had over the years - websites, music, goofy videos, etc.",
  },
  {
    id: 'web-dev',
    label: 'Web Development',
    description:
      'Here are some of my more recent web projects. Unfortunately, the web is an ever-evolving beast, so many of these either no longer exist, or have been redeveloped since I launched them. Archived links *might* be available upon request.',
    seo: 'These are some of my most recent web development projects.',
  },
  {
    id: 'music',
    label: 'Music',
    description:
      'In fourth grade, music grabbed me by the ear and never let go. Until I discovered web development, it was my primary passion. Here are a few of the highlights over the years.',
    seo: 'Music was my first passion, and I&rsquo;ve had a TON of musical ventures along the way.  Here are some of the highlights.',
  },
  // {
  //   id: 'photo',
  //   label: 'Photography',
  //   description:
  //     "Along the way, I wound up picking up a camera and found that I kinda liked shooting photos as well. It's never really been a *passion* per se, but it's fun when I have the time.  Enjoy!",
  // },
  {
    id: 'misc',
    label: 'Other Stuff',
    description: 'Here are some other random things I&rsquo;ve done.',
    seo: "Here are some other random things I've done.",
  },
]

export const projects = [
  {
    id: 'vickery',
    rotate: -0.812,
    title: 'Vickery Trading Co',
    client: 'Vickery Trading Co',
    year: '2024',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Boots',
    logo: '/images/work/logos/vickery-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-vickery.jpg',
		screenshot: '/images/work/screenshots/vickery-screenshot.png',
    url: '',
    media: '',
    mediaType: '',
    skills: [
      'HTML',
      'CSS',
      'JS',
      'Custom Shopify Themeing',
      'Website Design',
      'Store Design/Organization',
    ],
    notes:
      '<p>For the first time in almost 20 years, I&rsquo;ve found myself in need of a full portfolio website.  I have to say, it was really fun getting to build something for <strong><em>myself</em></strong> for a change.</p>\
      <p>I needed to slap this together ASAP, so it kinda reminded me of when my wife and I were looking at houses years ago.  We visited one old house that was OBVIOUSLY flipped really fast for a quick sale.  There were places where the paint was still wet and even dripping.  So, welcome to my hastily slapped together website.  Sorry about the wet paint.</p>\
      <p>I built this site using <a href="https://nextjs.org" target="_blank">Next.js</a>, with hosting by <a href="https://vercel.com" target="_blank">Vercel</a>.  I have to say, Next.js/Vercel is such a wonderful development experience.  I started working with Next.js with the Mizzen+Main website, and I don&rsquo;t think I would choose anything else at this point.  It&rsquo;s just so easy.</p>\
      <p>I&rsquo;m also introducing my new branding, including my new official brand color, <code>#B00075</code> (get it?). Apparently, it&rsquo;s called &ldquo;<a href="https://www.color-name.com/hex/b00075" target="_blank">Flirt</a>&rdquo; &#129300;. I never would have chosen a hot pink for myself, but I think this is a case where the color chose me.  It&rsquo;s actually really grown on me.</p>',
  },
  {
    id: 'bootsified',
    rotate: 0.456,
    title: 'Boots \'23',
    client: 'Boots',
    year: '2023',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Boots',
    logo: '/images/work/logos/bootsified-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-bootsified2023.jpg',
		screenshot: '/images/work/screenshots/boots2023b-screenshot.png',
    url: '',
    media: '',
    mediaType: '',
    skills: ['HTML', 'CSS', 'JS', 'Next.js/React', 'Website Design', 'Logo Design'],
    notes:
      '<p>For the first time in almost 20 years, I&rsquo;ve found myself in need of a full portfolio website.  I have to say, it was really fun getting to build something for <strong><em>myself</em></strong> for a change.</p>\
      <p>I needed to slap this together ASAP, so it kinda reminded me of when my wife and I were looking at houses years ago.  We visited one old house that was OBVIOUSLY flipped really fast for a quick sale.  There were places where the paint was still wet and even dripping.  So, welcome to my hastily slapped together website.  Sorry about the wet paint.</p>\
      <p>I built this site using <a href="https://nextjs.org" target="_blank">Next.js</a>, with hosting by <a href="https://vercel.com" target="_blank">Vercel</a>.  I have to say, Next.js/Vercel is such a wonderful development experience.  I started working with Next.js with the Mizzen+Main website, and I don&rsquo;t think I would choose anything else at this point.  It&rsquo;s just so easy.</p>\
      <p>I&rsquo;m also introducing my new branding, including my new official brand color, <code>#B00075</code> (get it?). Apparently, it&rsquo;s called &ldquo;<a href="https://www.color-name.com/hex/b00075" target="_blank">Flirt</a>&rdquo; &#129300;. I never would have chosen a hot pink for myself, but I think this is a case where the color chose me.  It&rsquo;s actually really grown on me.</p>',
  },
  {
    id: 'mizzen',
    rotate: -0.234,
    title: 'Mizzen+Main',
    client: 'Mizzen+Main',
    year: '2018-2023',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Mizzen+Main',
    logo: '/images/work/logos/mizzen-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-mizzen.jpg',
		screenshot: '/images/work/screenshots/mizzen-screenshot.jpg',
    url: '',
    media: '/images/work/video/mizzen-walkthrough-web.mp4',
    mediaType: 'walkthrough',
    skills: [
      'HTML',
      'CSS',
      'JS',
      'Next.js/React',
      'Liquid',
      'Custom Shopify Themeing',
      'Site Management',
    ],
    notes:
      '<p>After 20+ years building websites for clients, my time with <strong>Mizzen+Main</strong> was my first chance to have my own "baby". I was the Sr Manager of Web Development for Mizzen+Main, which meant I was in charge of everything to do with the website.  I handled 90% of the front-end development for the site, and managed a team of developers for the rest. Mizzen is a Shopify store, and when I started, we were on the older Liquid platform.</p>\
      <p>In 2022, I was able to lead our team through transitioning to a more modern "headless" site, using React/Next.js and Sanity CMS, while pulling in product data through the Shopify APIs. This is a massive site, and performed extremely well as the company grew. I&rsquo;m SUPER proud of the work I was able to do at Mizzen.</p>\
      <p>Since I&rsquo;ve left, the site has gone through some significant changes, so unfortunately I can only show a video of the site from my time there.</p>',
  },
  {
    id: 'the-release',
    rotate: 0.987,
    title: 'The Release',
    client: 'The Beta Release (AKA Boots)',
    year: '2021',
    projectType: 'Song',
    category: 'music',
    agency: '',
    logo: '/images/work/logos/thebetarelease-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-thebetarelease.jpg',
		screenshot: '/images/work/screenshots/thebetarelease2-screenshot.jpg',
    url: '',
    media:
      'https://soundcloud.com/the-beta-release/the-release?in=the-beta-release/sets/first-four-demo/s-GJmPNOdFLgZ&si=3532862927724aefafb5105e8ec32838&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing',
    mediaType: 'audio',
    skills: [
      'Writing',
      'Arranging',
      'Production',
      'Bass Guitar',
      'Guitar',
      'Synths',
      'Drum Programming',
    ],
    notes:
      "<p>Ah, 2020... What a miserable year you were. Well, being locked down for months with the family was tough, but during that time, I wound up starting a little &ldquo;COVID project&rdquo; that turned out to be something special.</p>\
    <p>Over the years, I'd always thought about making my own album, but never really had the inspiration to do it. In the effort to pass the time during the pandemic, I decided to &ldquo;just do it&rdquo; and start recording whatever came to mind at the moment.  The result was my new music project, <strong>The Beta Release</strong>.</p>\
    <p>I was able to get 4 songs recorded before life kicked in again, and this - an instrumental called <em>The Release</em> - is the first one that's ready to share.  The other 3 are mostly hard rock remakes of old electro-pop songs from the 80s/90s, but since I'm not really a vocalist, I'm working on bringing in someone else to handle that. Hopefully I'll be able to share those soon as well.</p>\
    <p>I hope that life will allow me to continue this project into the future.  I have a many more ideas for song remakes.  We'll see if they ever make it out of my head.</p>",
  },
  {
    id: 'canalesco',
    rotate: -0.654,
    title: 'Canales & Co',
    client: 'Canales & Co',
    year: '2018',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/canalesco-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-canalesco.jpg',
		screenshot: '/images/work/screenshots/canalesco-screenshot.jpg',
    url: 'http://canalesco.com',
    media: '',
    mediaType: '',
    skills: ['HTML', 'CSS', 'JS', 'CraftCMS', 'Twig'],
    notes:
      "<p>The last website I built while I was at Good Work was for a design agency in Austin, called <strong>Canales & Co</strong>.  They specialize in product branding, with much of their work in the beverage industry. I absolutely LOVE these guys.  SO creative, and simply beautiful designs.</p>\
      <p>They knew what they wanted for a website, but came to us to build it.  So, I took their designs and built a custom content-managed website, using CraftCMS.  I wanted to make it so they could easily keep it updated with their latest work, so I put a lot of time into the CMS.  This project was almost 100% photography, with a complex masonry layout.  CraftCMS's customizeable content blocks really came in handy here.</p>\
      <p>The Canales & Co website is still one of my all-time favorites, and I'd love to be able to work with their designs again sometime in the future.  Go check them out!</p>",
  },
  {
    id: 'vale',
    rotate: 0.123,
    title: 'Vale Counseling',
    client: 'Vale Counseling',
    year: '2017',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Boots',
    logo: '/images/work/logos/vale-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-vale.jpg',
		screenshot: '/images/work/screenshots/vale-screenshot.jpg',
    url: 'https://valecounseling.boots.media/',
    media: '',
    mediaType: '',
    skills: ['HTML', 'CSS', 'JS', 'CraftCMS', 'Twig', 'Website Design', 'Logo Design'],
    notes:
      "<p>This was kind of a fun &ldquo;passion project&rdquo; for my wife's former counseling practice. It's several years old now, but it's still a favorite of mine, and still serves the practice well.</p>\
    <p>I handled everything from design to development - even helping them with a new logo - and it's got a super nice, fully custom CMS, built with CraftCMS. I'm really proud of this one.</p>\
    <p>They recently changed their website, so for my portfolio purposes, the link here is to a staging version of the site I built.</p>",
  },
  {
    id: 'adopted',
    rotate: -0.901,
    title: 'AdoptED',
    client: 'Gladney Center for Adoption',
    year: '2015',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/adopted-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-adopted.jpg',
		screenshot: '/images/work/screenshots/adopted-screenshot.jpg',
    url: '',
    media: '/images/work/video/adopted-walkthrough-web.mp4',
    mediaType: 'walkthrough',
    skills: ['HTML', 'CSS', 'JS', 'ExpressionEngine'],
    notes:
      "<p>One of the big clients we had when I was working at Switch was the Gladney Center for Adoption. <strong>AdoptED</strong> was a program of theirs dedicated to promoting adoption through education. We were able to have a little fun with the design of this site, and push the boundaries a bit with the layout and interface. I love its look and feel, and had a lot of fun developing it.</p>\
      <p>It was built using ExpressionEngine, which at the time was one of the best CMS platforms around. It also featured big, bold, fullscreen images and aggressive colors, along with some slick parallaxing that was all the rage at the time. I still think it's pretty cool.<p>\
      <p>Sadly, it no longer exists, so the best I can do is show you a walkthrough video.</p>",
  },
  {
    id: 'tots-nuggs',
    rotate: 0.345,
    title: 'Tots & Nuggs',
    client: 'Boots',
    year: '2022',
    projectType: 'Song',
    category: 'music',
    agency: '',
    logo: '/images/work/logos/bootsified-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-totsandnuggs.jpg',
		screenshot: '/images/work/screenshots/totsandnuggs-screenshot.jpg',
    url: '',
    media:
      'https://soundcloud.com/the-beta-release/tots-nugs?si=ac1f0deed53e4c989695d00be8cad362&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing',
    mediaType: 'audio',
    skills: [
      'Writing',
      'Arranging',
      'Production',
      'Vocals',
      'Bass Guitar',
      'Guitar',
      'Drum Programming',
    ],
    notes:
      '<p>So, sometimes a dad has to do some silly stuff to get his kids to go along with things. For whatever reason, my boys would moan every time I would tell them we were having chicken nuggets and tater tots for dinner (it&rsquo;s a regular around here). To lighten the mood, I started singing an off-the-cuff song about &ldquo;Tots & Nuggs&rdquo;, which would annoy them/make them laugh enough to where they would stop whining. Over time, the song evolved in my head, so I decided to record it as a goof. And the rest is history.</p>\
      <p>Fun fact: this is the first time I&rsquo;ve ever sung lead vocals on a song. After 40 years of playing in bands, I guess it took chicken nuggets and tater tots to give me enough inspiration to try it. <pre>¯\\_(ツ)_/¯</pre></p>',
  },
  {
    id: 'maridoe',
    rotate: -0.567,
    title: 'Maridoe Golf Club',
    client: 'Maridoe Golf Club',
    year: '2017',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/maridoe-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-maridoe.jpg',
		screenshot: '/images/work/screenshots/maridoe-screenshot.jpg',
    url: 'https://maridoe.com/',
    media: '',
    mediaType: '',
    skills: ['HTML', 'CSS', 'JS', 'CraftCMS', 'Twig'],
    notes:
      '<p><strong>Maridoe Golf Club</strong> is a relatively new golf course in the Dallas area.  We were brought on pretty early to create a very &ldquo;high-end&rdquo; feeling site to promote the new club.  This site features lots of slick animated transitions, and a beautiful fullscreen drone video of the course as a background for the homepage.  This one still hold up pretty well, I think.  It&rsquo;s fully content managed through a custom CraftCMS build.</p>',
  },
  {
    id: 'criquet',
    rotate: 0.789,
    title: 'Criquet Shirts',
    client: 'Criquet Shirts',
    year: '2018',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/criquet-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-criquet.jpg',
		screenshot: '/images/work/screenshots/criquet-screenshot.jpg',
    url: '',
    media: '',
    mediaType: '',
    skills: ['HTML', 'CSS', 'JS', 'Liquid', 'Custom Shopify Themeing'],
    notes:
      "<p><strong>Criquet Shirts</strong> is a fun men's clothing company based in Austin, TX.  As they were starting to really take off, I was brought in to give the site a refresh.  I built a new custom Shopify theme for the site that really took things to the next level.  Unfortunately, they've since changed their theme, and there isn&rsquo;t really a good archive of the site in its older state. The best I can do is a cool shot of the homepage.</p>",
  },
  {
    id: 'the-laurel',
    rotate: -0.123,
    title: 'The Laurel',
    client: 'The Laurel Texas',
    year: '2016',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/thelaurel-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-thelaurel.jpg',
		screenshot: '/images/work/screenshots/thelaurel-screenshot.jpg',
    url: '',
    media: '/images/work/video/thelaurel-walkthrough-web.mp4',
    mediaType: 'walkthrough',
    skills: ['HTML', 'CSS', 'JS', 'CraftCMS', 'Twig'],
    notes:
      '<p><strong>The Laurel</strong> is a high-end wedding and special event facility in the Dallas area.  Switch created a knock-out of a design for their launch, and I was able to make this a real marquis site.  It was all focused around photography, which was sourced from local photographers who had worked events there.  As part of the massive CMS (CraftCMS), we were able to cite each of the photos throughout the site with links to the vendor sites.</p>\
    <p>The website featured beautiful full screen photos, along with some really creative parallaxed interfaces and animated transitions.  This was one of my absolute favorite sites I built at that time, and the custom CMS I built was a thing of beauty (if I may say so myself).  Just about every element of the site was content-managed by the client through the CMS.</p>',
  },
  {
    id: 'the-interrogation',
    rotate: 0.678,
    title: 'The Interrogation',
    client: 'Boots',
    year: '2022',
    projectType: 'Video',
    category: 'misc',
    agency: 'Boots',
    logo: '/images/work/logos/bootsified-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-theinterrogation.jpg',
		screenshot: '/images/work/screenshots/theinterrogation-screenshot.jpg',
    url: '',
    media: 'https://youtu.be/lhPjK90urgk',
    mediaType: 'video',
    skills: ['Screenplay', 'Direction', 'Cinematography', 'Video Editing', 'Acting?'],
    notes:
      '<p>While I was at Mizzen+Main, we would do silly videos for social media and internal stuff once in a while.  In 2022, each of the company&rsquo;s &ldquo;all-hands&rdquo; meetings featured one of the departments of the corporate HQ.  Each of the employees of the featured department was tasked to make a short video, where they would answer a set of questions about themselves.  It was a simple get-to-know-you thing for the company.</p>\
    <p>Well, the videos I had made while I was there always featured my sons (I think they&rsquo;re pretty awesome), so when it was my turn to make the &ldquo;get-to-know-you&rdquo; video, I kinda went a little overboard with it.  The boys and I had a nighttime video shoot at the office, with them questioning me as if they were 70s-era TV detectives interrogating a perp.  It was so much fun, and we actually knocked it out in about and hour.  Not bad for a couple rookie actors.  They totally killed it, and I couldn&rsquo;t be more proud of how this silly little video turned out. </p>\
    <p>WARNING: Contains some inside jokes that won&rsquo;t make any sense outside the office.</p>',
  },
  {
    id: 'jordan',
    rotate: -0.456,
    title: 'Jordan Tourism Board',
    client: 'Jordan Tourism Board North America',
    year: '2004',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Boots',
    logo: '/images/work/logos/jordan-logo-noir2.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-jordan.jpg',
		screenshot: '/images/work/screenshots/jordan-screenshot.jpg',
    url: '',
    media: '',
    mediaType: '',
    skills: ['HTML', 'CSS', 'JS', 'Flash Programming', 'Website Design'],
    notes:
      '<p>While freelancing in 2004, I received a random call from a friend, saying the <strong>Jordan Tourism Board</strong> (where they worked) was looking for someone to build a new website for them.  They were looking to make a new push to promote the Kingdom of Jordan to American tourists.  So naturally, I said, &ldquo;Let&rsquo;s <em>DO</em> this!&rdquo; <pre>¯\\_(ツ)_/¯</pre></p>\
    <p>Mind you, this was 2004, so I didn&rsquo;t build it AT ALL like I would today &mdash; lots of Flash, and every page was hardcoded, with common elements included with SHTML.  For a site this large, that meant a LOT of individual files to keep up with.  Yet, it turned out great, and they loved it.</p>\
    <p>The website launched in late 2004, and was unveiled at an international tourism conference by King Abdullah II himself.  As part of my compensation, I was invited to Jordan for a VIP tour of the country the following year, including a visit to the Royal Palace (unfortunately, the King was away at the time.  It was an amazing adventure that still seems like a dream to me, and I found a great love and respect for Jordan through that experience.</p>\
    <p>Of course, this site is pretty ancient when it comes to the web, so no functional archives are available (#RIPFlash).  I was lucky to even piece together a screenshot of the Flash homepage.</p>',
  },
  {
    id: 'electrico',
    rotate: 0.912,
    title: 'Live at the Glass Cactus',
    client: 'Passing Strangers',
    year: '2007',
    projectType: 'Music Video',
    category: 'music',
    agency: '',
    logo: '/images/work/logos/bootsified-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-possumkingdom3.jpg',
		screenshot: '/images/work/screenshots/electrico-screenshot.jpg',
    url: '',
    media: 'https://www.youtube.com/watch?v=CWyxoTYKXnw&list=PLeo8qWiBmVzenP3aZ7_QCaD2vGS4CUhj4',
    mediaType: 'video',
    skills: ['Bass Guitar', 'Video Production'],
    notes:
      "<p>This is a playlist of songs from a live DVD that my band, <strong>Passing Strangers</strong>, made in 2007.  It was filmed at a pretty awesome venue in Grapevine, TX, called The Glass Cactus.</p>\
    <p>The shoot was self-produced, so we borrowed a bunch of cameras, and asked some buddies of ours to handle the handheld shots.  Aside from the poor white balance on one of the main cameras (you live and you learn, I guess) and a drum cam with a loose lens, it all came out great.  Our drummer mixed down the audio, and I produced the video.</p>\
    <p>Unfortunately, YouTube decided to reduce the quality of the videos at some point, so the stream is pretty ugly now.  If I can ever find the original files, I'll upload them again.</p>",
  },
  {
    id: 'gladney',
    rotate: -0.789,
    title: 'Gladney Center',
    client: 'Gladney Center for Adoption',
    year: '2018',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/gladney-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-gladney.jpg',
		screenshot: '/images/work/screenshots/gladney-screenshot.jpg',
    url: 'https://adoptionsbygladney.com/',
    media: '',
    mediaType: '',
    skills: ['HTML', 'CSS', 'JS', 'CraftCMS', 'Twig'],
    notes:
      '<p>One of the big clients we had when I was working at Switch was the <strong>Gladney Center for Adoption</strong>, and this is their main website.  Switch&rsquo;s design for the site was another knockout, and once again, I was able to stretch my legs a bit with the development.  It&rsquo;s a MASSIVE site, with a custom CMS built with CraftCMS.  This was by far the most intense CMS build I&rsquo;ve had, but it all turned out great.  The site is still in use today (2023)</p>\
    <p>A couple of the highlights of this site are the <a href="https://adoptionsbygladney.com/i-want-to-adopt" target="_blank">&ldquo;What kind of adoption is right for me?&rdquo; questionaire</a>, and the fun timeline-style layout of <a href="https://adoptionsbygladney.com/about/history-timeline" target="_blank">their history page</a>.</p>',
  },
  {
    id: 'dock-bass-solo',
    rotate: 0.234,
    title: 'Bass Solo @ The Dock',
    client: 'Passing Strangers',
    year: '1998',
    projectType: 'Music Video',
    category: 'music',
    agency: '',
    logo: '/images/work/logos/bootsified-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-basssolodock.jpg',
		screenshot: '/images/work/screenshots/basssolodock-screenshot.jpg',
    url: '',
    media: 'https://www.youtube.com/watch?v=Bys69-mxu6E',
    mediaType: 'video',
    skills: ['Bass Guitar'],
    notes:
      '<p>This was a slow Sunday evening, the fourth night of four, at The Dock in Jackson, MS &mdash; one of our regular stops along the gulf coast back in the day.  After blowing it out for a packed house the three nights before, this was definitely a <em>tired</em> &ldquo;performance&rdquo;, but the handful of people watching didn&rsquo;t seem to care.  I would play a variation of this solo just about every night.  As far as I know, this is the only footage there is of it.</p>',
  },
  {
    id: 'falchi',
    rotate: -0.345,
    title: 'The Falchi Building',
    client: 'Jametown Urban Management',
    year: '2016',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/falchi-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-falchi.jpg',
		screenshot: '/images/work/screenshots/falchi-screenshot.jpg',
    url: '',
    media: '/images/work/video/falchi-walkthrough-web.mp4',
    mediaType: 'walkthrough',
    skills: ['HTML', 'CSS', 'JS', 'CraftCMS', 'Twig'],
    notes:
      "<p><strong>The Falchi Building</strong> is a historic office building in Long Island City, New York.  This website was part of a hip, modern rebranding of the building to represent the new renaissance happening in the area.  I loved the clean, bold design, and was able to add some cool flourishes in the build. The site featured some nice, subtle parallaxing, and an SVG map of the floors, with hyperlinks to each of the floors&rsquo; availabilities.  It's a pretty simple, information-based site, but still one of my faves.</p>",
  },
  {
    id: 'birds-of-play',
    rotate: 0.654,
    title: 'Birds of Play',
    client: 'Birds of Play FC',
    year: '2017',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Boots',
    logo: '/images/work/logos/birdsofplay-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-birdsofplay.jpg',
		screenshot: '/images/work/screenshots/birdsofplay-screenshot.jpg',
    url: 'http://birdsofplay.boots.media/',
    media: '',
    mediaType: '',
    skills: ['HTML', 'CSS', 'JS', 'CraftCMS', 'Twig', 'Website Design', 'Logo Design'],
    notes:
      '<p>When one of the dads of a 4-6 year olds YMCA soccer team is a web developer, you sometimes find yourself with a WAY over-engineered website for the team.  That is definitely the case with the <strong>Birds of Play FC</strong> website.</p>\
    <p>It started with me designing a logo for their uniforms, which led to me cranking out a fully-CMS&rsquo;ed website, with season schedule and game scores (even though they didn&rsquo;t actually keep an official score).  This was really a fun project for me, trying to make this little team of little kids look like a real soccer club.  We all had a lot of fun with it.  Sadly, the team only lasted one year, so the site now just exists as a historical record.</p>\
    <p>The best part of the site was a large photo gallery from the games and practices, which I set up to pull from a Flickr group that the parents could post to.  Unfortunately, Flickr changed their rules a while back, and the photos had to be taken down.  So if you see a bunch of broken image links, there you have it.</p>',
  },
  {
    id: 'bluebird',
    rotate: -0.890,
    title: 'Bluebird Real Estate',
    client: 'Bluebird Real Estate',
    year: '2018',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Good Work',
    logo: '/images/work/logos/bluebird-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-bluebird.jpg',
		screenshot: '/images/work/screenshots/bluebird-screenshot.jpg',
    url: 'https://bbre1.com/',
    media: '',
    mediaType: '',
    skills: ['HTML', 'CSS', 'JS', 'CraftCMS', 'Twig'],
    notes:
      '<p><strong>Bluebird Real Estate</strong> is a real estate company based in the Crested Butte, CO, area.  The website was designed to be a simple, clean site, to really feature the property photographs.  It featured a custom CMS built with CraftCMS, and is integrated with their MLS account to pull in their available properties.  While the MLS integration took a while to work out the kinks, we finally nailed it, and the site has performed very well for them ever since.</p>',
  },
  {
    id: 'hinge',
    rotate: 0.567,
    title: 'Hinge Analytics',
    client: 'Hinge Analytics',
    year: '2015',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/hinge-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-hinge.jpg',
		screenshot: '/images/work/screenshots/hinge-screenshot.jpg',
    url: '',
    media: '/images/work/video/hinge-walkthrough-web.mp4',
    mediaType: 'walkthrough',
    skills: ['HTML', 'CSS', 'JS', 'ExpressionEngine'],
    notes:
      '<p><strong>Hinge Analytics</strong> was a... well, I&rsquo;m not actually sure what they were.  Something about &ldquo;consulting&rdquo; and &ldquo;results&rdquo;, with a ton of generic biz-speak in between.  Fortunately for me, they wanted a website that would really stand out, and Switch and I gave them one.</p>\
    <p>From the looping, fullscreen background video of a chimpanzee pounding on a computer for the homepage, to the bottom of this single-page scroller, it was nothing like what you&rsquo;d expect from a typical &ldquo;analytics company&rdquo;.  The site was playful, top-to-bottom, which was a lot of fun for me to develop.  It also featured a custom CMS built with ExpressionEngine, so the client could update their biz-speak to their hearts desire.</p>\
    <p>OK... In all honesty, I LOVED this website, and the client was a total joy to work with, but since the company didn&rsquo;t last very long, it *might* not have been the best branding decision.  But hey, I&rsquo;m just the developer.  I leave the branding to the experts.</p>',
  },
  {
    id: 'see-you-today',
    rotate: -0.098,
    title: 'See You Today',
    client: 'Interface',
    year: '1990',
    projectType: 'Music Video',
    category: 'music',
    agency: 'Boots',
    logo: '/images/work/logos/bootsified-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-seeyoutoday.jpg',
		screenshot: '/images/work/screenshots/seeyoutoday-screenshot.jpg',
    url: '',
    media: 'https://www.youtube.com/watch?v=trqFaoDmofs',
    mediaType: 'video',
    skills: ['Bass Guitar'],
    notes:
      "<p>The first real gigging band I was in was <strong>Interface</strong>, based in Dallas, TX.  We started in 1990 and quickly became one of the better known bands in the scene.  We later even had a song that got significant airplay on regional alt-rock stations, but weren&rsquo;t able to break through before things fell apart in 1994.  It's too bad...  we were pretty good.</p>\
    <p>This video was shot at the world-famous Southfork Ranch (home of the Ewings from TV&rsquo;s <em>Dallas</em>), where we were the headliner for the 1990 SMU homecoming celebration.  Sure... laugh all you want.  But we looked and sounded pretty fly for 1990.  This was probably the biggest crowd I'd played for at the time, so you can practically see the stage fright in my eyes.  Assuming you can peel you eyes away from my badass bolo tie and tux shirt, under the oversized blazer with rolled up sleeves.  Grrrr, baby!</p>",
  },
  {
    id: 'dallas-guitar-repair',
    rotate: 0.876,
    title: 'Dallas Guitar Repair',
    client: 'Dallas Guitar Repair',
    year: '2016',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Boots',
    logo: '/images/work/logos/dallasguitarrepair-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-dallasguitarrepair.jpg',
		screenshot: '/images/work/screenshots/dallasguitarrepair-screenshot.jpg',
    url: 'http://dallasguitarrepair.boots.media/',
    media: '',
    mediaType: '',
    skills: ['HTML', 'CSS', 'JS', 'CraftCMS', 'Twig', 'Website Design', 'Logo Design'],
    notes:
      "<p>This one is interesting. A friend of mine has run a local guitar repair shop, called <strong>Dallas Guitar Repair</strong>, since the late 80s. He has a website for his business, but it was pretty old and had a lot of issues. In December of 2016, I was inspired to build him a new website and logo as a surprise Christmas gift.  I had an idea in my head, and a little extra time over the holidays, so I knocked out a quick website and sent him a link.  Obviously, this was his business, and I would make sure it represented him as he'd like, so I left the door open to make any changes that would suit him.</p>\
    <p>Well, he declined the site.  He never really said why, but just that he wasn&rsquo;t interested, which is totally his prerogative. So now it&rsquo;s just a neat little side project I made that will never get used.</p>\
    <p>It sucks for me, because I really like it, and it came together real quick.  I built it with CraftCMS, and it has a super intuitive CMS built specifically for a guitar shop.  Maybe one day I'll find a shop that could use it.  <pre>¯\\_(ツ)_/¯</pre></p>",
  },
  {
    id: 'pregnancy-hotline',
    rotate: -0.543,
    title: 'Pregnancy Hotline',
    client: 'Gladney Center for Adoption',
    year: '2015',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/gladney-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-pregnancyhotline.jpg',
		screenshot: '/images/work/screenshots/pregnancyhotline-screenshot.jpg',
    url: '',
    media: '/images/work/video/pregnancyhotline-walkthrough-web.mp4',
    mediaType: 'walkthrough',
    skills: ['HTML', 'CSS', 'JS', 'ExpressionEngine'],
    notes:
      '<p>One of the big clients we had when I was working at Switch was the <strong>Gladney Center for Adoption</strong>.  This was their "Pregnancy Hotline" website, for pregnant women who needed help.  Switch&rsquo;s design for the site was another knockout, and once again, I was able to stretch my legs a bit with the development.  The site actually won a DSVC Bronze Award in 2016.</p>\
    <p>It features a custom CMS, built with ExpressionEngine.  We also integrated it with their primary CRM to pull in all the data for their prospective adoptive parents.  Women could come to the site and search through the hundreds of prospective families.  Once they found families that seemed like a good fit, they could message them and start a conversation.  I was SUPER proud of this website.  We were told by Gladney that they saw a major increase in contacts once this site launched.  That&rsquo;s what I love to hear.  :)</p>',
  },
  {
    id: 'new-years-day',
    rotate: 0.321,
    title: 'New Years Day',
    client: 'Blood Red Sky',
    year: '2006',
    projectType: 'Music Video',
    category: 'music',
    agency: 'Boots',
    logo: '/images/work/logos/bloodredsky-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-newyearsday.jpg',
		screenshot: '/images/work/screenshots/newyearsday-screenshot.jpg',
    url: '',
    media: 'https://www.youtube.com/watch?v=0w_aBtBo7PI',
    mediaType: 'video',
    skills: ['Bass Guitar', 'Video Production'],
    notes:
      "<p>Back in 2006, my band at the time (Passing Strangers) had the idea to do a side project.  Our singer could kill it on U2 songs, so we thought it would be fun to start a U2 tribute band.  We called it <strong>Blood Red Sky</strong>.  The Dallas Hard Rock Cafe booked us to premiere our new band for their St Patrick's Day celebration, so we spent the couple months leading up to it practicing hard and worked up about 30 songs &mdash; many of them were already in our regular playlist.</p>\
    <p>I also built a pretty complex live video production, that would show clips from the corresponding music videos while we played the songs, along with animated graphics and transitions.  All in all, it was an awesome show.</p>\
    <p>Sadly... after months of hard work and practice, working up a really intricate show, we were SO burned out on these songs that we actually never did it again :face_palm:.  This was actually the one and only show we did with the full production.  Also, we hired someone to shoot video of the show, but they turned out to not know ANYTHING about shooting a live band.  The video he took was pretty awful, so I did the best I could and edited what I could salvage, mixed in with some still photos taken by a photographer who was there.  Even though the video doesn&rsquo;t really do the show justice, I think it still turned out pretty cool.</p>",
  },
  {
    id: 'doubler',
    rotate: -0.687,
    title: 'Double R',
    client: 'Double R Brand by Ravi Ratan',
    year: '2015',
    projectType: 'Website',
    category: 'web-dev',
    agency: 'Switch',
    logo: '/images/work/logos/doubler-logo-noir.png',
    screenshotNoir: '/images/work/screenshots/comic-screenshot-doubler.jpg',
		screenshot: '/images/work/screenshots/doubler-screenshot.jpg',
    url: '',
    media: '/images/work/video/doubler-walkthrough-web.mp4',
    mediaType: 'walkthrough',
    skills: ['HTML', 'CSS', 'JS', 'Liquid', 'Custom Shopify Themeing'],
    notes:
      '<p>Double R is a custom dress shirt company for women.  This was my first time to build custom Shopify themes, and I think it turned out great.  The big feature of the site was a multi-stage video walkthrough, to help women take their measurements and input them correctly for their order.  Overall, I throught the design was really nice.</p>\
    <p>Sadly, this version of the site no longer exists, and I haven&rsquo;t been able to get an archive of the best parts of the site.</p>',
  },
]
